### ISSUE TITLE
chart file structure

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-digital-twin-registry#101]
> Helm charts must be located inside the /charts directory of the Git repository.

is ok but maybe to avoid confustion '/backend' you can move or rename it

**Comment by LuLeRoemer** [comment]
Yes, afaik it is: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/tree/main/charts

**Comment by FaGru3n** [comment]
> Yes, afaik it is: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/tree/main/charts

Sure... i get it 😉  but first start for users of the registry would be leading repo and the underlying folders and if there is only a chart folder they know "i have to deloy or use your helm charts" just a hint, don´t get me wrong. 🤝

**Comment by LuLeRoemer** [comment]
@FaGru3n thanks for the hint. We separate the source code into different folders using maven subprojects.
