### ISSUE TITLE
CPU and Memory Ressource Requests

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-digital-twin-registry#103]
Hi Dev SPOC's 

personally i think this are sane vaules, so i will mark it as checked, but you could also add ressource request definitions.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#example-1

https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/191c008558c25ba365f5f6e510b591e8280c08fe/charts/registry/values.yaml#L73-L77

**Comment by LuLeRoemer** [comment]
@FaGru3n thanks for the hint. We will look at this in the next PI.

**Comment by tunacicek** [comment]
Hi, 
the issue is done in https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/88 .
So we can close this issue.
