### ISSUE TITLE
Allow to provide PostgreSQL creds via a k8s secret

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/sldt-digital-twin-registry#117]
**Is your feature request related to a problem? Please describe.**
It's a _bad practise_ to provide credentials in plain text to a helm chart. Also if there is some automatism in place which provides the DB and the credentials, it's currently not possible with the helm chart to use this in an easy way -> you need to manually copy the values into your `values.yaml` configuration.

**Describe the solution you'd like**
Provide a way to take the DB creds from a kubernetes secret ([example](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-with-data-from-multiple-secrets))

**Describe alternatives you've considered**
Another solution could be to provide the possibility to define additional `environment` like it's done in the [EDC helm charts](https://github.com/eclipse-tractusx/tractusx-edc/blob/89410f66737a7b3d8680ca89a30883934d2e22a3/charts/tractusx-connector/templates/deployment-controlplane.yaml#L314-L333)

**Comment by tunacicek** [comment]
Done. Issue can be closed.
