### ISSUE TITLE
Rename helm chart to reflect product name

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sldt-digital-twin-registry#119]
Hi,

this is not release relevant but im preparing the release right now and your helm chart name caught my eye:

'registry'

Can you please reevaluate the name of it to make it better/clearer.

Tx,

Sigi
![Screenshot 2023-05-17 at 10 59 21](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/assets/47592287/4980004a-9659-475c-b01d-e6504b97569a)

**Comment by agg3fe** [comment]
Hi,
Thanks for sharing this. We will have a look into this.

**Comment by tunacicek** [comment]
Done. Issue can be closed.
