### ISSUE TITLE
Apply `init-script-configmap.yaml` only if keycloak is enabled

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/sldt-digital-twin-registry#124]
## Describe the bug

With the current helm chart the file [`keycloak/init-script-configmap.yaml`](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/1d8ed72b4d1ada56e3c0876bf700c2776a24d40c/charts/registry/templates/keycloak/init-script-configmap.yaml) will always be deployed to the cluster - doesn't matter if keycloak was enabled or not.

Additionally, the ConfigMap has a fix name: that means, it's not possible to run two DTRs in the same K8s namespace.

### To Reproduce

1. Deploy the helm chart to a k8s cluster with `enableKeycloak: false`
2. Run `kubectl get cm init-script-vol`

### Expected behavior

If I disable the keycloak setup, I don't want to have anything polluting my environment in context of the keycloak setup.

## Possible Implementation

Add an if statement to the template based on the value `enableKeycloak`. Additionally use a generated name based on the release name (like it's done at the [`registry/registry-deployment.yaml`](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/1d8ed72b4d1ada56e3c0876bf700c2776a24d40c/charts/registry/templates/registry/registry-deployment.yaml#L21))

**Comment by tunacicek** [comment]
Hi, 
fix is done. 
Issue will be closed.
