### ISSUE TITLE
500 on non-UUID shell-descriptor/id

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-digital-twin-registry#147]
[The spec](https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShellRegistryServiceSpecification/V3.0.1_SSP-001)  states that the id attribute in the [AssetAdministrationShellDescriptor ](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/70f91c0b3bb6091125d2335b19b05a01db16c5cf/backend/src/main/java/org/eclipse/tractusx/semantics/registry/model/ShellDescription.java#L30)and [SubmodelDescriptor ](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/70f91c0b3bb6091125d2335b19b05a01db16c5cf/backend/src/main/java/org/eclipse/tractusx/semantics/registry/model/SubmodelDescription.java#L30) are strings. Yet, in this Repo, they're both UUIDs.

Posting non-UUIDs against the DTR returns 500.

```bash
curl --location 'aas/shell-descriptors' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer token' \
--data '{
  "id": "https://sap.com/myidentifier/1234",
  "semanticId": {
    "type": "ExternalReference",
    "keys": [
      {
        "type": "GlobalReference",
        "value": "urn:bamm:io.catenax.material_for_recycling:1.1.0#MaterialForRecycling"
      }
    ]
  },
  "endpoints": [
    {
      "protocolInformation": {
        "href": "https://edc.data.plane/sometin/api/v3.0/submodel",
        "endpointProtocol": "HTTP",
        "endpointProtocolVersion": [
          "1.1"
        ],
        "subprotocol": "DSP",
        "subprotocolBody": "sometin",
        "subprotocolBodyEncoding": "plain",
        "securityAttributes": [
          {
            "type": "NONE",
            "key": "NONE",
            "value": "NONE"
          }
        ]
      },
      "interface": "SUBMODEL-3.0"
    }
  ]
}'
```

**Comment by Pamela-Cofinity** [comment]
@arnoweiss I was lookking to pick up this issue. Can you please tell me should the code implementation be changed to accept String instead of uuid or the spec needs to be corrected?

**Comment by arnoweiss** [comment]
This is an implementation bug (which I haven't reproduced since opening this issue a long time ago). The IDTA's spec of allowed values in the `id` field likely isn't gonna change anytime soon.

**Comment by tunacicek** [comment]
Bug is fixed. With the newest version it is possible to save shells (shell-descriptors) with non UUID.
