### ISSUE TITLE
Improper Error Handling

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-digital-twin-registry#155]
Currently, the DTR returns HTTP 500 for a variety of requests. As it seems, HTTP 400 is only returned on a missing shell-descriptor/id attribute. When included, arbitrary json-structures will cause an internal server error.

```http
POST /api/v3.0/shell-descriptors HTTP/1.1
Host: dtreg.de
Content-Type: application/json
Accept: application/json
Authorization: Bearer 
Content-Length: 84
{
  "id": "12312312-91f0-4dac-a730-eaa1d35e035c",
  "myarbitraryjson": "structure"
}

```
returns 
```json
{
    "timestamp": "2023-07-07T08:21:26.864+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/v3.0/shell-descriptors"
}
```

The relevant openAPI files define appropriate behavior for registries in cases of errors. Implementing it with expressive "text"-messages what part of the json-structure failed inbound validation will not only be a further step toward spec-compliance but also greatly ease integration efforts with sldt-digital-twin-registry

**Comment by agg3fe** [comment]
Hi,
Thanks for creating this issue. We will work on this and provide you with the feedback as soon as we resolve this.

**Comment by shijinrajbosch** [comment]
Hi @arnoweiss ,

The issue is fixed and please find the screenshot below :

![image](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/assets/136349699/4726ddf4-5cbf-4dc6-99e0-c29c13d07a44)


Please request you to check from your side.
