### ISSUE TITLE
Wrong handling of specficAssetIds and externalSubjectIds

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-digital-twin-registry#169]
There's an issue with how [`specificAssetIds`](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/SpecificAssetId) are handled. According to the specification, the type of an `externalSubjectId` is [`Reference`](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Reference). Both are part of the [`AssetAdministrationShellDescriptor`](https://app.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0.1#/components/schemas/AssetAdministrationShellDescriptor). However, the sldt-digital-twin-registry (registry-0.3.11) behaves strange when handling requests that include it. 

### Reproduce

Create correct AAS-Descriptor:

```http
POST /api/v3.0/shell-descriptors HTTP/1.1
Host: myDtr.de
Content-Type: application/json
Accept: application/json
Authorization: Bearer mytoken
Content-Length: 516

{
    "id": "urn:uuid:myAasId",
    "idShort": "myAas",
    "specficAssetIds": [
        {
            "name": "manufacturerPartId",
            "value": "BPN:123-345-567103",
            "externalSubjectId": {
                "type": "ExternalReference",
                "keys": [
                    {
                        "type": "GlobalReference",
                        "value": "BPNL:someBpnOfAssetOwner"
                    }
                ]
            }
        }
    ],
    "submodelDescriptors":[]
}
```
### Actual Behavior
returns HTTP 201
```json
{
    "description": [],
    "displayName": [],
    "idShort": "myAas",
    "id": "urn:uuid:myAasId",
    "specificAssetIds": [],
    "submodelDescriptors": []
}
```

### Expected Behavior:
returns HTTP 201

```json
{
    "id": "urn:uuid:myAasId",
    "idShort": "myAas",
    "specficAssetIds": [
        {
            "name": "manufacturerPartId",
            "value": "BPN:123-345-567103",
            "externalSubjectId": {
                "type": "ExternalReference",
                "keys": [
                    {
                        "type": "GlobalReference",
                        "value": "BPNL:someBpnOfAssetOwner"
                    }
                ]
            }
        }
    ],
    "submodelDescriptors":[]
}
```

### More Context

The DTR also accepts the POST Requests containing other forms of `externalSubjectIds`. However, like with the case described above, the externalSubjectId is unconsidered.

```http
POST /api/v3.0/shell-descriptors HTTP/1.1
Host: mydtr.de
Content-Type: application/json
Accept: application/json
Authorization: Bearer myToken
Content-Length: 285

{
    "id": "urn:uuid:myAasIdWithStringSubject",
    "idShort": "myAas",
    "specficAssetIds": [
        {
            "name": "manufacturerPartId",
            "value": "BPN:123-345-567103",
            "externalSubjectId": "myStiring"
        }
    ],
    "submodelDescriptors":[]
}
```

also returns 201. In this case, this should be a bad request.

```json
{
    "description": [],
    "displayName": [],
    "idShort": "myAas",
    "id": "urn:uuid:myAasIdWithStringSubject",
    "specificAssetIds": [],
    "submodelDescriptors": []
}
```

I think, the fundamental error is in handling "externalSubjectIds" as String instead of Reference.
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/6325efb9b8d47a7c9e69d751022735babd8ea42c/backend/src/main/java/org/eclipse/tractusx/semantics/registry/model/ShellIdentifier.java#L52

**Comment by tunacicek** [comment]
Hi @arnoweiss ,

you have a typo in your payload. You use specficAssetIds instead of specificAssetIds. Please try it again.
