### ISSUE TITLE
QG4: TRG 2.05 .tractusx metafile in a proper format

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#191]
At .tractusx metadata file field 'leadingRepository' doesn't contain proper URL to repository:

As per [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5):

leadingRepository: "LEADING_PRODUCT_REPOSITORY_URL"

Updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/189

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

we corrected this issue with PR  "feat:Corrected LEADING_PRODUCT_REPOSITORY_URL #196". If everything is fine, then please close this issue.
