### ISSUE TITLE
QG4: TRG 7.02 - License and Copyright header

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#199]
Hi @bs-sili,

There is quite few files missing Copyright headers:

	.github/workflows/helm-release.yml
	.github/workflows/kics.yml
	.tractusx
	backend/src/main/resources/catena-template.css
	backend/src/test/java/org/eclipse/tractusx/semantics/registry/HealthCheckTest.java
	charts/registry/templates/tests/test-connection.yaml
	charts/registry/templates/tests/test-credentials.yaml
	charts/registry/templates/tests/test-script-configmap.yaml
	pom.xml

Updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/189

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

for this issue we created a PR and also merged it:
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/204

**Comment by tomaszbarwicki** [comment]
hey @bs-sili, I'm sorry for reopening the issue, just spotted the .tractusx file has wrong comments format for copyright header, please use '#' as for normal yaml format file. The current one makes it unhandled by the dashboard. Thanks in advance!

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki ,
no problem. I just now created a PR for new .tractusx file:
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/214
