### ISSUE TITLE
Issue with lookup API of digital twin registry

### ISSUE THREAD

**Issue by rahulrkhapre** [eclipse-tractusx/sldt-digital-twin-registry#211]
When registering a DT in the central DTR (incl. externalSubjectIDs), customer is not able to lookup the twin via specificAssetID when using the SAME user (tenant) which he used while creating it. When using a different user (tenant), which is mentioned in externalSubjectIDs, client could successfully lookup the twin via specificAssetID.

 Current deployed version is 0.2.0-M13-multi-tenancy.  
 
 In the currently deployed version, We are also facing delay in lookup api response. When there are 13000 twins, time taken to lookup is more than 1.5 minutes. In the earlier version **v0.2.0-M12-multi-tenancy** performance of the lookup api was faster. The idea behind using above version was "Digital Twin Registry will not be visible by default unless you explicitly enable them." 
 
 This slowness behaviour was observed after the hot fix was deployed 

 Please advice if we need to upgrade to any specific or latest version to fix these two issues.

**Comment by ma3u** [comment]
Error can be replicated in 3.1 and fixed internally. Further tests in INT (Beta) will happen:
https://semantic-hub.int.cofinity-x.com/semantics/registry/swagger-ui/index.html

We will also fix this issue for the next release 23.12 in the decentralized DTR as enablement service.

**Comment by agg3fe** [comment]
We have done the performance improvements in the decentral DTR and released the latest image(v0.3.17).

**Comment by tunacicek** [comment]
Issue will be closed. In case of perfomance issues with the newest version, please create a new issue.
