### ISSUE TITLE
Postman Collection → "POST Create Shell" Call → Missing security attributes

### ISSUE THREAD

**Issue by jerzy-wachowiak** [eclipse-tractusx/sldt-digital-twin-registry#220]
# Postman Collection
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/366970100962a3532f1d8dd2bb4be1ecdaea5674/docs/development/postman/tractusx-dtr-aas-3.0.0-collection.json#L21

# Body of  "POST Create Shell" Call  in v0.3.16-M1 
`"securityAttributes": [
              {
                "type": "NONE"
              }
            ]`

Error message from cx-registry-registry-svc logs:
"2023-09-07T13:21:15.454Z ERROR 1 --- [qtp373437697-48] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: null value in column "attribute_key" of relation "submodel_security_attribute" violates not-null constraint"

# Should be
`"securityAttributes": [
              {
                "type": "NONE",
                "key": "Security Attribute key",
                "value": "Security Attribute value"
              }
            ]`

**Comment by jerzy-wachowiak** [comment]
The same implies to other calls in the Postman collection...

**Comment by bs-sili** [comment]
Hi @jerzy-wachowiak,

thank you for your hint. The key and value are mandatory. We will update the collection and let you know. Meanwhile, if you want, you can add these two values (key and value in the security attribute) and then it should work for you.

**Comment by tunacicek** [comment]
Done. Issue can be closed.
