### ISSUE TITLE
reconsider helm chart name for next release

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sldt-digital-twin-registry#222]
Hi,

your helm chart currently is called 'registry'.

Please revisit this to make it more 'digital twin registry' for the next release

You can see how your helm chart looks like from a naming perspective in the upcoming release notes i'm currently preparing.

**Comment by bs-sili** [comment]
Hi @Siegfriedk,
thank you for your hint. We gonna have a look into that.

**Comment by tunacicek** [comment]
We renamed our helm chart to digital-twin-registry.
