### ISSUE TITLE
Insecure password exposure in values.yaml

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#247]
Creating issue related to hardcoded password in the values.yaml file:

At line https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/0498dc12d15d624cb31bdfda939d27a85b964f87/charts/registry/values.yaml#L93 password is set to 'password'. Suggest to use existing postgresql secret with auto-generated password.

updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/246

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

is this QG relevant or can it solved after QG?
At the moment we have a ticket about that topic created for another application. We are also already in contact with the DevSecOps team about that topic.

**Comment by tomaszbarwicki** [comment]
Hi @bs-sili, I'd say this one can be fixed afterwards.

**Comment by tunacicek** [comment]
Done. Issue will be closed.
