### ISSUE TITLE
TRG 5.11 Upgradeability

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#248]
Please follow [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11/) to add upgrade step to the helm test workflow. Good example you can find in the discovery finder https://github.com/eclipse-tractusx/sldt-discovery-finder/blob/main/.github/workflows/helm-test.yml, please make sure conditions allow execution of the steps while workflow is ran manually.

Updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/246

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

should be fixed with #244 . PR is already merged
