### ISSUE TITLE
Relative INSTALL.md path pointing to 404 at dockerhub

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#249]
Please change relative path of INSTALL.md from README.md used at https://hub.docker.com/r/tractusx/sldt-digital-twin-registry which currently points to 404 error.

Updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/246

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,

can we do this after QG? We also have this Issue in other applications and we wanted to make a update after QG for all of our maintained services.

**Comment by tomaszbarwicki** [comment]
Hi @bs-sili, it's actually a legal stuff so I'd say it should be fixed, however I think doing that on main should be enough.
