### ISSUE TITLE
unique IdShort is mandatory

### ISSUE THREAD

**Issue by KilianHaag** [eclipse-tractusx/sldt-digital-twin-registry#257]
The swagger schema lists the IdShort as not-mandatory, but a request without the IDShort results in a 500 Server Error caused by a NullPointerException.
As far as I can see, this PR added a check, whether the IdShort is unique. https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/229
With the previous chart version 0.3.24, this was not the case.

Tested with: chart version 0.3.27

Working call:
![MicrosoftTeams-image](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/assets/124401943/c603e3e7-1827-4ccc-ad7a-b5e011619f6a)

Erroneous call:
![MicrosoftTeams-image (1)](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/assets/124401943/f54ae8f2-4046-4f2b-a1b2-436339810e0e)
[ddtr-logs.txt](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/files/13488057/ddtr-logs.txt)

**Comment by tunacicek** [comment]
Hi @KilianHaag ,
thanks for the hint. With the new version, the idshort is mandatory and unique as describe in the PR. 

Handling of IdShort for DTR changes:
IdShort is unique on shell level. Idshort can be exists only one time in the database (tenant)
IdShort of submodelDescriptor is unique inside a shell. Uniqueness on shellId and idShort and Idshort of submodelDescriptors are unique.

We will fix the openApi yml to mark idShort as mandatory.

**Comment by KilianHaag** [comment]
Ok, thank you for the update.

**Comment by tunacicek** [comment]
Hi @KilianHaag ,
i checked it again. Idshort must be unique and not mandatory (Based on AAS Standard). We fixed the bug here: 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/276
