### ISSUE TITLE
Helm chart with version 0.3.29 is not available

### ISSUE THREAD

**Issue by ghost** [eclipse-tractusx/sldt-digital-twin-registry#263]
Why is a digital-twin-registry helm chart [registered in the `index.yaml` with the version `0.3.29`](https://github.com/eclipse-tractusx/charts/blob/732a14cc2a92d00634cf6f0cd70b6ecb25a2a34b/dev/index.yaml#L5195C1-L5217C20), although version 0.3.29 is not available?

## Steps to reproduce

```shell
$ helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
$ helm pull tractusx-dev/digital-twin-registry              
Error: failed to fetch https://github.com/eclipse-tractusx/sldt-digital-twin-registry/releases/download/digital-twin-registry-0.3.29/digital-twin-registry-0.3.29.tgz : 404 Not Found
```

Fetching the 0.3.28 is working:

```shell
$ helm pull tractusx-dev/digital-twin-registry --version 0.3.28
$ ls digital-twin-registry-0.3.28.tgz
digital-twin-registry-0.3.28.tgz
```

**Comment by tunacicek** [comment]
Hello, could you please try again?
I followed your steps and was able to download it.
