### ISSUE TITLE
Deployment fails on Azure Database for PostgreSQL flexible server

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-digital-twin-registry#278]
Issue when deploying on Azzure Database.

Reported in: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/225

Part of this issue is also the ticket: https://github.com/eclipse-tractusx/sig-release/issues/347

JIRA ticket 1396

**Comment by RazvanZmau** [comment]
[jerzy-wachowiak](https://github.com/jerzy-wachowiak)  Please let us know if we (SLDT team) still need to follow any activity inside this ticket.
Thank you

**Comment by tunacicek** [comment]
PR is created. 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/453
