### ISSUE TITLE
Update to AAS v.3.1

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-digital-twin-registry#284]
Evolution of Asset Administration Shell

3.1 update

Description:
New API has to be developed in DigitalTwinRegistry.
https://app.swaggerhub.com/apis/Plattform_i40/DiscoveryServiceSpecification/V3.1.0_SSP-001#/Asset%20Administration%20Shell%20Basic%20Discovery%20API/SearchAllAssetAdministrationShellIdsByAssetLink

The input parameters(name, value) should be plain text without any encryption.

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/468
