### ISSUE TITLE
Provide registry helm chart in eclipse-tractusx/e2e-testing

### ISSUE THREAD

**Issue by tunacicek** [eclipse-tractusx/sldt-digital-twin-registry#285]
A general project is set up to deploy all components via a helm chart.

https://github.com/eclipse-tractusx/e2e-testing

As the digital twin registry is also a part of the decentralized environment, we need to provide a helm chart in this repository for the digital-twin-registry.

Further background information:

We had already started to provide an all-in-one helm chart.

https://github.com/eclipse-tractusx/charts/pull/11

This PR will no longer be merged. Because: 

Following the same approach, multiple teams will be collaborating in this eclipse-tractusx/e2e-testing repo.

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/347
