### ISSUE TITLE
Extend DTR APIs for Access management

### ISSUE THREAD

**Issue by tunacicek** [eclipse-tractusx/sldt-digital-twin-registry#287]
This story introduces validation based on the access rules. Following workflow needs to be implemented: 
1. Load access rules based on BPN (via Header) and filter the response. 
2. Start validation and return the filtered shell. More details of the validation logic is described in the following: 
<img width="1333" alt="Screenshot 2024-01-15 at 13 25 21" src="https://github.com/eclipse-tractusx/sldt-digital-twin-registry/assets/115143031/b23ec325-f739-4931-a14c-6370ba1713b5">

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/417
