### ISSUE TITLE
Implement new DTR validation API (for submodel request)

### ISSUE THREAD

**Issue by tunacicek** [eclipse-tractusx/sldt-digital-twin-registry#289]
Implement the new DTR validation API with following logic: 
1. Validate, if incoming request is allowed to call the submodel endpoint. 
1.1. Load access rules based on BPN
1.2. Load submodel-descriptor and validate -> result of request: 200 OK or 403 forbidden (TBD)

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/417
