### ISSUE TITLE
Concept of CRUD API for Access management APIs 

### ISSUE THREAD

**Issue by tunacicek** [eclipse-tractusx/sldt-digital-twin-registry#291]
Define/finalize the CRUD API for access management.
[access-control-openapi_flat_v6.yaml.zip](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/files/14163187/access-control-openapi_flat_v6.yaml.zip)

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/417

**Comment by istvan-nagy-epam** [comment]
Hi,
the OpenAPI specification is now available in the DTR repository as well. Please find the two parts here:
- API: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/7165366cfa621e7f7681cb8fae3dd1a1f32b1b68/access-control-service-sql-impl/src/main/resources/static/access-control-openapi.yaml
- Schemas: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/7165366cfa621e7f7681cb8fae3dd1a1f32b1b68/access-control-service-sql-impl/src/main/resources/static/access-control-openapi_schemas.yaml

> [!NOTE]
> The specification had some minor changes compared to the zipped variant attached to the ticket description. Please make sure to review and use the latest version if you are integrating your application with the DTR!
