### ISSUE TITLE
[TRG 1.04] Diagrams as code

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#327]
Hi team,

There is a number of diagrams in sldt-digital-twin-registry/docs/img repository stored as .png files. I
Please consider ahering to [TRG 1.04](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-4/), describing the process of creation and modification / change to other suggested methods.

Updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/326

**Comment by tunacicek** [comment]
Hi @tomaszbarwicki ,
as discussed, for the feature diagrams, we will create and provide them in PUML or Mermaid.

**Comment by tunacicek** [comment]
We transformed each diagram to puml. Issue can be closed.
