### ISSUE TITLE
 Separate notice for docker images

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sldt-digital-twin-registry#332]
Please create separate notice for docker images following [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06/).

Currently the notice for docker images is present in the README.md, the requirement is to have it in separate file, close to Dockerfile and be published in dockerhub.

Updates https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/326

**Comment by tunacicek** [comment]
Hi @tomaszbarwicki ,
the notice file is available for docker images: 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/DOCKER_NOTICE.md
