### ISSUE TITLE
DTR in Tractus X tutorial >> Data Provisioning

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-digital-twin-registry#381]
See link --> https://eclipse-tractusx.github.io/docs/tutorials/e2e/boost/provideData/

**Comment by RazvanZmau** [comment]
Child of https://github.com/eclipse-tractusx/sig-release/issues/634

**Comment by tunacicek** [comment]
Currently a fork branch exists with all changes. There is a new section for DTR Tutorial: 
https://github.com/jkbquabeck/eclipse-tractusx.github.io/blob/main/docs/tutorials/e2e/boost/DTR_Tutorial.md
 
And one open PR: 
https://github.com/jkbquabeck/eclipse-tractusx.github.io/pull/6
