### ISSUE TITLE
DTR in Tractus X tutorial >> Restrict Data

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-digital-twin-registry#383]
See the documentation from the following link --> https://eclipse-tractusx.github.io/docs/tutorials/e2e/boost/restrictData

**Comment by RazvanZmau** [comment]
child of https://github.com/eclipse-tractusx/sig-release/issues/634

**Comment by tunacicek** [comment]
Currently a fork branch exists with all changes. There is a new section for DTR Tutorial: 
https://github.com/jkbquabeck/eclipse-tractusx.github.io/blob/main/docs/tutorials/e2e/boost/DTR_Tutorial.md
 
And one open PR to describe the access control in DTR: 
https://github.com/jkbquabeck/eclipse-tractusx.github.io/pull/6
