### ISSUE TITLE
Analyse pattern: Special characters in SpecificAssetId

### ISSUE THREAD

**Issue by tunacicek** [eclipse-tractusx/sldt-digital-twin-registry#384]
Currently it is not possible to save a shell with specificAssetIds which includes special characters in the value. 
The goal of this topic is to check if the pattern allows special characters or not.

**Comment by gerbigf** [comment]
There's also been an issue created by Cofinity (https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/391) and a PR proposed: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/392
