### ISSUE TITLE
Filter sub-models based on sub-model type -> change to globalreference type instead of sub-model type

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-digital-twin-registry#404]
Currently the filterSubmodels (for the access management) based on semanticIds includes a check on type=submodel. 
But the semanticId object uses the type GlobalReference instead of Submodel. 

The check on type=submodel is not needed and can be ignored/deleted

**Comment by tunacicek** [comment]
PR is created: 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/405
