### ISSUE TITLE
[EDC 0.7.1] Shell Lookup from EDC Data Plane 

### ISSUE THREAD

**Issue by tanweersalah** [eclipse-tractusx/sldt-digital-twin-registry#419]
EDC  == 0.7.1

While requesting the Catalog from registry for a particular assetId, I am getting the empty list, 

while requesting directly to DTR I am getting the response, 

<img width="1145" alt="Screenshot 2024-06-01 at 12 31 29 PM" src="https://github.com/eclipse-tractusx/digital-product-pass/assets/31222891/178666aa-f3b1-4207-bab6-4ec9f1b6631f">

But when the same assetid is being lookup from the EDC Data Plane , I am getting empty result. 

<img width="1165" alt="Screenshot 2024-06-01 at 12 31 54 PM" src="https://github.com/eclipse-tractusx/digital-product-pass/assets/31222891/56c1339f-121b-461e-9e1c-a5548a5d6e7b">

**Comment by tanweersalah** [comment]
Also i am able to fetch all shell descriptors from Dataplane , just when I look for specific Asset Id , I am getting empty result. 

<img width="1075" alt="Screenshot 2024-06-03 at 11 20 35 AM" src="https://github.com/eclipse-tractusx/tractusx-edc/assets/31222891/300cd083-89e6-465b-8f47-e7bf3086271c">

**Comment by agg3fe** [comment]
HI @tanweersalah, the visibility of the shell is based on the externalSubjectId in the specificAssetId. Only BPNs which are listed  in the SpecificAssetId are able to show the shell. See the documentation please for more details: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/tree/main/docs#:~:text=dev%40eclipse.org-,Access,-control%20to%20Digital
