### ISSUE TITLE
`v0.3.23` DockerHub DTR-Image does not Support Look Up by multiple `SpecificAssetId`s

### ISSUE THREAD

**Issue by efiege** [eclipse-tractusx/sldt-digital-twin-registry#424]
### Description
In DockerHub there is one `0.3.23` version available for the DTR: 
https://hub.docker.com/r/tractusx/sldt-digital-twin-registry/tags?page=&page_size=&ordering=&name=0.3.23

When checking out the corresponding `v0.3.23` tag, the `GET /lookup/shells?assetIds=` endpoint accepts `List<byte[]> assetIds`. However this just enables to pass exactly one `SpecificAssetId`. 

This seems to be fixed with https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/243. However those chnages are not integrated in the `v0.3.23` tag, but in the `registry-0.3.23` tag. There also seems to be quite some differences between those tags: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/compare/registry-0.3.23...v0.3.23

Which one is the correct tag to use for the `0.3.23` release? The image published at DockerHub seems to be using the `v0.3.23` tag.

**Comment by agg3fe** [comment]
Hi @efiege , Could you please use the latest version of DTR https://github.com/eclipse-tractusx/sldt-digital-twin-registry/releases/tag/digital-twin-registry-0.4.11.
This should already include the required changes.

**Comment by efiege** [comment]
Hey @agg3fe, thanks for the answer!

We want to be compatible to Tractus-X Release 24.03, which states to use the DTR in version `0.3.23`:
https://eclipse-tractusx.github.io/CHANGELOG/#updated-1

As such it is not yet possible to transition to a newer version.

**Comment by arnoweiss** [comment]
@efiege
Are you witnessing this behavior in conjunction with an 0.5.x tractusx-edc? Then it could be this: https://github.com/eclipse-edc/Connector/issues/4022

Are you using a single `assetIds` query parameter with a single encoded json-object? Then it could be https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/395#issuecomment-2057072216

**Comment by efiege** [comment]
Thanks for providing these references @arnoweiss, this helped a lot. The problem has been related to https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/395#issuecomment-2057072216

I have been able to use the `/lookup/shells?assetIds` endpoint now.
