### ISSUE TITLE
Update AAS interface to bugfix v3.0.2

### ISSUE THREAD

**Issue by thomas-henn** [eclipse-tractusx/sldt-digital-twin-registry#443]
New Bugfix Release (3.0.2) is available. Useful links: 

- https://industrialdigitaltwin.org/en/content-hub/aasspecifications
- https://github.com/admin-shell-io/aas-specs/releases/tag/IDTA-01001-3-0-1_schemasV3.0.8 Metamodel
- https://github.com/admin-shell-io/aas-specs-api/releases/tag/v3.0.2
- https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShellRegistryServiceSpecification/V3.0.2_SSP-001

### **Asset AdminstrationShellRegisty - Compare v3.0.2_SSP-001 with v3.0.2_SSP-001**

**1. GET    /description**
Changes in Media types

**2. DELETE & GET & PUT: /shell-descriptors/{aasIdentifier}**
  Parameter:
    - Changed aasIdentifier in path to use string instead of byte

**3. DELETE & GET & PUT:/shell-descriptors/{aasIdentifier}/submodel-descriptors/{submodelIdentifier}}**
  Parameter:
    - Changed aasIdentifier and submodelIdentifier in path to use string instead of byte

**4. PATTERN for all fields changed**

### **Discovery - Compare v3.0.2_SSP-001 with v3.0.2_SSP-001**
**1. Changed aasIdentifier to use string instead of byte**
**2. PATTERN for all fields changed**

**Comment by agg3fe** [comment]
Changelog:
https://admin-shell-io.github.io/aas-specs-antora/IDTA-01002/v3.1/changelog.html#_changes_w_r_t_v3_0_1_to_v3_0_2

**Comment by tunacicek** [comment]
@thomas-henn , @agg3fe :
PR is created https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/455

I've added some smaller TODOs to the openAPI YML file that need to be clarified.
