### ISSUE TITLE
Add TruffleHog to the repositories

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sldt-digital-twin-registry#461]

**Comment by agg3fe** [comment]
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/464
https://github.com/eclipse-tractusx/sldt-semantic-hub/pull/294
https://github.com/eclipse-tractusx/sldt-bpn-discovery/pull/164
https://github.com/eclipse-tractusx/sldt-discovery-finder/pull/162

**Comment by tunacicek** [comment]
PRs are merged. Can we close this issue? 
@agg3fe
