### ISSUE TITLE
Keycloak Admin UI loading indefinitely

### ISSUE THREAD

**Issue by marctuerke** [eclipse-tractusx/sldt-digital-twin-registry#481]
### Current Behavior
The Keycloak admin user interface is stuck in an endless loading loop. The Keycloak attempts to send a request to the host within the cluster, although I have forwarded the port of the Keycloak service.

<img width="1726" alt="Bildschirmfoto 2024-11-12 um 14 43 31" src="https://github.com/user-attachments/assets/a4211a13-62eb-4ffe-bca7-6f1d984f7e1e">

<img width="551" alt="Bildschirmfoto 2024-11-12 um 14 43 46" src="https://github.com/user-attachments/assets/23202046-4a27-4392-9f0a-f1acbc229923">

<img width="557" alt="Bildschirmfoto 2024-11-12 um 14 44 38" src="https://github.com/user-attachments/assets/f1f91f47-c835-46ad-bbbf-641c527bf04f">

### Expected Behavior
Accessible admin user interface without configuring an ingress for the Keycloak.
 
### Steps To Reproduce
I deployed the official helm chart on my Kubernetes cluster and want to access the Keycloak by forwarding the port of the Keycloak service.

**Comment by arnoweiss** [comment]
@tunacicek - can you take a look? 🙏🏻
