### ISSUE TITLE
Github Pages returns 404

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-digital-twin-registry#60]
The [launched Github environment](https://eclipse-tractusx.github.io/sldt-digital-twin-registry/) that's supposed to hold the docs, returns a 404.

![image](https://user-images.githubusercontent.com/86715435/215479309-2ceb4af3-d37a-483f-8518-1fc8becb3672.png)

**Comment by LuLeRoemer** [comment]
The GitHub pages environment you mentioned is solely used for Helm Chart releases. Our documentation can be found in the [README.md](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/README.md) and in the [docs folder](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/tree/main/docs).
In case you are actually looking for our Helm releases on a technical level, take a look [here](https://eclipse-tractusx.github.io/sldt-digital-twin-registry/index.yaml).
