### ISSUE TITLE
Digital twin secret for deploying IRS

### ISSUE THREAD

**Issue by neischlah** [eclipse-tractusx/sldt-digital-twin-registry#67]
Hi everyone!

I would like to receive a digital twin secret as instructed here:
https://eclipse-tractusx.github.io/docs/kits/Data%20Chain%20Kit/Operation%20View/

Thanks!

**Comment by LuLeRoemer** [comment]
Thanks for your comment. You no longer require a pull secret, as our images are publicly available [here](https://github.com/catenax-ng/product-semantics/pkgs/container/sldt-digital-twin-registry).
