### ISSUE TITLE
interface of "SubModel Description Endpoints" /w EDC must be "SUBMODEL-1.0RC02"

### ISSUE THREAD

**Issue by miwamasa** [eclipse-tractusx/sldt-digital-twin-registry#68]
in https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/docs/documentation.md

![image](https://user-images.githubusercontent.com/730771/224916483-7c7e88cf-d848-4160-bf3e-ef4cb0c62f1c.png)

**Comment by LuLeRoemer** [comment]
Could you please elaborate on the problem you have?
