### ISSUE TITLE
Digital twin Registry secret for development needed

### ISSUE THREAD

**Issue by pm-at-fujitsu** [eclipse-tractusx/sldt-digital-twin-registry#70]
Hello,
I would like to receive a digital twin registry secret as instructed [here](https://github.com/catenax-ng/tx-item-relationship-service/tree/presentation/local-deployment/charts/full-irs) and [here](https://eclipse-tractusx.github.io/docs/kits/Data%20Chain%20Kit/Operation%20View/) to setup my development environment.

**Comment by LuLeRoemer** [comment]
Thanks for your comment. You no longer need pull secrets, as our images are publicly available [here](https://github.com/catenax-ng/product-semantics/pkgs/container/sldt-digital-twin-registry).
