### ISSUE TITLE
INSTALL.md

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-digital-twin-registry#92]
You could overthink to write down your install instructions into a separate INSTALL.md 

> If this is too much text, it can be moved into a INSTALL.md file.

https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/main/README.md#deploy-using-helm-and-k8s

**Comment by LuLeRoemer** [comment]
@FaGru3n Thanks, we'll certainly look into it. :)
