### ISSUE TITLE
persist data

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-digital-twin-registry#95]
Hi found some persistance values.
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/77503744fb91553a545d2d9ad5c0c183e2aa54ab/charts/registry/values.yaml#L81

Please have a look on https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2/#how to generate a persistance volume claim to not lose data by accident.

**Comment by LuLeRoemer** [comment]
Hi @FaGru3n thanks for the hint. We use the [postgresql Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/postgresql) as a dependency. There a PVC is included.
